version: 0.0
os: linux
files:
  - source: build/
    destination: /var/www/html/
  - source: scripts/httpd.conf
    destination: /etc/httpd/conf/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
