version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: eljo
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: eljo
