version: 0.0

phases:
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Performing npm module installation
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Running npm build for AWS...
      - npm run buildAWS
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: build
