version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Running npm build...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/
