#!/bin/bash
isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi

# remove default httpd.conf
rm -f /etc/httpd/conf/httpd.conf

# copy httpd.conf with proxy
cp scripts/httpd.conf /etc/httpd/conf/httpd.conf